now in this commit I get Id_token from index.jsp to my servlet(MainAuthorizationServlet) and i use different google's library that i get from maven repo the problem was I face when i run tu build the war from my docker the war file has not lib's and due to this i had NoClassDefFoundError exception.problem solved by usinf project structure artificat and put the libs to the war lib :)